name: static
on:
  # Runs on pushes to "main"
  push:
    branches:
      - main
  # Allows manual dispatch
  workflow_dispatch:

# Sets permissions of the GITHUB_TOKEN to allow deployment to GitHub Pages
permissions:
  contents: read
  pages: write
  id-token: write
  packages: write

# Allow only one concurrent deployment, skipping runs queued between the run in-progress and latest queued.
# However, do NOT cancel in-progress runs as we want to allow these production deployments to complete.
concurrency:
  group: "static"
  cancel-in-progress: false

jobs:
  static:
    uses: from-static/actions/.github/workflows/static.yml@v2
    with:
      deploy_to_github_pages: false
  deploy:
    # Our deploy process requires the `static` job to complete first.
    needs: [static]
    runs-on: ubuntu-latest
    # Checkout repo to get the dockerfile
    steps:
    - uses: actions/checkout@v4
      with:
        name: Checkout
    # Login to github container registry
    - name: Login to GitHub Container Registry
      uses: docker/login-action@v3
      with:
        registry: ghcr.io
        username: ${{ github.repository_owner }}
        password: ${{ secrets.GITHUB_TOKEN }}

    # Download the artifact that was generated by the `static` job.
    - uses: actions/download-artifact@v4
      with:
        name: github-pages    
    # Build docker container 
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3
    - name: Set up QEMU
      uses: docker/setup-qemu-action@v3  
    - name: Build
      uses: docker/build-push-action@v6
      with:
        platforms: linux/amd64,linux/arm64
        context: .
        push: true
        load: false
        tags: ghcr.io/${{ github.repository }}:${{ github.ref_name }}
        cache-from: type=gha
        cache-to: type=gha,mode=max